### PR TITLE
Post #650 UEHelpers improvements

### PR DESCRIPTION
**Pull request by igromanru**
With suggestions from @narknon I've made following changes:
- Added `nil` checks for functions that return a property that could potentially be `nil`  if the object is of the wrong type or if something changes in the UE base code  
- Added (back) `FindAllOf("PlayerController") or` to improve `Controlls` loop performance in the `GetPlayerController` function for the majority of the game which use `APlayerController`

**None of the changes are breaking, they only make the code safer**

Additionally I added missing Lua types for the classes [UE4SS](https://docs.ue4ss.com/lua-api/classes/ue4ss.html#ue4ss) and [UnrealVersion](https://docs.ue4ss.com/lua-api/classes/unrealversion.html#unrealversion).
- Each function is twice there because both call types are valid, with `.` and with `:`

### Tests
Tested the code as before.
With this Lua code:
```lua
local Major, Minor, Hotfix = UE4SS:GetVersion()
print(string.format("UE4SS v%d.%d.%d\n", Major, Minor, Hotfix))
Major, Minor, Hotfix = UE4SS.GetVersion()
print(string.format("UE4SS v%d.%d.%d\n", Major, Minor, Hotfix))

print(string.format("UnrealVersion v%d.%d\n", UnrealVersion:GetMajor(),  UnrealVersion:GetMinor()))
print(string.format("UnrealVersion v%d.%d\n", UnrealVersion.GetMajor(),  UnrealVersion.GetMinor()))

local playerController = UEHelpers.GetPlayerController()
if playerController:IsValid() then
	print("playerController: " .. playerController:GetFullName())
else
	print("playerController invalid")
end
local player = UEHelpers.GetPlayer()
if player:IsValid() then
	print("player: " .. player:GetFullName())
else
	print("player invalid")
end
local gameEngine = UEHelpers.GetEngine()
if gameEngine:IsValid() then
	print("gameEngine: " .. gameEngine:GetFullName())
end
local gameViewportClient = UEHelpers.GetGameViewportClient()
if gameViewportClient:IsValid() then
	print("gameViewportClient: " .. gameViewportClient:GetFullName())
end
local world = UEHelpers.GetWorld()
if world:IsValid() then
	print("world: " .. world:GetFullName())
end
print("WorldDeltaSeconds: " .. UEHelpers.GetGameplayStatics():GetWorldDeltaSeconds(UEHelpers.GetWorldContextObject()))
local persistentLevel = UEHelpers.GetPersistentLevel()
if persistentLevel:IsValid() then
	print("persistentLevel: " .. persistentLevel:GetFullName())
else
	print("persistentLevel invalid")
end
local worldSettings = UEHelpers.GetWorldSettings()
if worldSettings:IsValid() then
	print("worldSettings: " .. worldSettings:GetFullName())
else
	print("worldSettings invalid")
end
local gameModeBase = UEHelpers.GetGameModeBase()
if gameModeBase:IsValid() then
	print("gameModeBase: " .. gameModeBase:GetFullName())
else
	print("gameModeBase invalid")
end
local gameStateBase = UEHelpers.GetGameStateBase()
if gameStateBase:IsValid() then
	print("gameStateBase: " .. gameStateBase:GetFullName())
else
	print("gameStateBase invalid")
end

local invalidObject = CreateInvalidObject()
print("invalidObject variable type: " .. type(invalidObject))
if invalidObject then
	print("invalidObject userdata type: " .. invalidObject:type())
	print("invalidObject IsValid:" .. tostring(invalidObject:IsValid()))
end
```
**Results**
In menu:
```
UE4SS v3.0.1
UE4SS v3.0.1
UnrealVersion v5.4
UnrealVersion v5.4
playerController: BP_PlayerController_C /Game/Maps/Map_MainMenu.Map_MainMenu:PersistentLevel.BP_PlayerController_C_2147479844
player: BP_MainMenuPawn_C /Game/Maps/Map_MainMenu.Map_MainMenu:PersistentLevel.BP_MainMenuPawn_C_2147479059
gameEngine: GameEngine /Engine/Transient.GameEngine_2147482467
gameViewportClient: GameViewportClient /Engine/Transient.GameEngine_2147482467:GameViewportClient_2147480061
world: World /Game/Maps/Map_MainMenu.Map_MainMenu
WorldDeltaSeconds: 0.016665998846292
persistentLevel: Level /Game/Maps/Map_MainMenu.Map_MainMenu:PersistentLevel
worldSettings: ESWorldSettings /Game/Maps/Map_MainMenu.Map_MainMenu:PersistentLevel.ESWorldSettings
gameModeBase: BP_GameModeMainMenu_C /Game/Maps/Map_MainMenu.Map_MainMenu:PersistentLevel.BP_GameModeMainMenu_C_2147479889
gameStateBase: GameState /Game/Maps/Map_MainMenu.Map_MainMenu:PersistentLevel.GameState_2147479849
invalidObject variable type: userdata
invalidObject userdata type: UObject
invalidObject IsValid:false
```
In game:
```
UE4SS v3.0.1
UE4SS v3.0.1
UnrealVersion v5.4
UnrealVersion v5.4
playerController: BP_PlayerController_C /Game/Maps/Locations/S02L06.S02L06:PersistentLevel.BP_PlayerController_C_2147443355
player: BP_Ship_Player_C /Game/Maps/Locations/S02L06.S02L06:PersistentLevel.BP_Ship_Player_C_2147442420
gameEngine: GameEngine /Engine/Transient.GameEngine_2147482467
gameViewportClient: GameViewportClient /Engine/Transient.GameEngine_2147482467:GameViewportClient_2147480061
world: World /Game/Maps/Locations/S02L06.S02L06
WorldDeltaSeconds: 0.016665600240231
persistentLevel: Level /Game/Maps/Locations/S02L06.S02L06:PersistentLevel
worldSettings: ESWorldSettings /Game/Maps/Locations/S02L06.S02L06:PersistentLevel.ESWorldSettings
gameModeBase: BP_GameModeBase_C /Game/Maps/Locations/S02L06.S02L06:PersistentLevel.BP_GameModeBase_C_2147447355
gameStateBase: GameState /Game/Maps/Locations/S02L06.S02L06:PersistentLevel.GameState_2147446661
invalidObject variable type: userdata
invalidObject userdata type: UObject
invalidObject IsValid:false
```

### CODE REVIEW

**Comment by narknon** [comment]
I also think our helpers themselves should give error messages about when things aren't found or aren't valid.

**Comment by UE4SS** [comment]
Considering we're checking for `Controller`, not just `PlayerController`, should we even have the `IsPlayerController` check ?
Doesn't that check make the inclusion of finding just `Controller` irrelevant since we're looking for `PlayerController` as well anyway ?

**Comment by igromanru** [comment]
> I'm not sure if IsPlayerController() has always existed and it also only returns true if the class is a PlayerController, so it will never return true if this falls back to the Controller search.

The function `AController::IsPlayerController()` exists since Unreal Engine v4.12, it was added 16.05.2016 with commit 496e06c3d5ef366576a8e92455d62f932f5679f8. The function IsLocalPlayerController() that I've now added as BackUp exists since 4.0.1. The only downside of IsLocalPlayerController is that it doesn't work on a server.  
The function `IsPlayerController()` is a part of the class `AController`, so that the developer of the game, who doesn't use APlayerController, can set the property `bIsPlayerController` in `AController` to `true`. Therefore, it can be assumed that game developers who develop their own player controller will set it to “true” there. But we'll never know until we actually find such a game and test it there.  
I don't think it's worth assuming that some game developers are cooking their own soup and doing what they want. And the previous approach of GetPlayerController was not accurate either. A valid PlayerController exists since the beginning of the game and is valid even if it does not control an APawn. A player can die and you can have a valid local PlayerController or a valid PlayerController on the server that no longer controls anything at a certain point in time.

> I also think our helpers themselves should give error messages about when things aren't found or aren't valid.

I disagree, Helpers should not behave any differently to UE4SS. The user should be able to handle errors as he want.  
I for example have extra functions like `LogError`, `LogDebug` etc. which always print `[ModName]` in front of each message and I don't want my mods to print random messages to the console that can't be traced back to my mod.  

> Considering we're checking for `Controller`, not just `PlayerController`, should we even have the `IsPlayerController` check ? Doesn't that check make the inclusion of finding just `Controller` irrelevant since we're looking for `PlayerController` as well anyway ?

A player controller is not just the APlayerController class. As you guys said, a game can have a custom controller for the player built on top of the `AController`. Therefore, the `AController` itself has a `bIsPlayerController` flag and the `IsPlayerController` function to determine that it is a controller that should control a player and not an NPC.

**Comment by UE4SS** [comment]
> > Considering we're checking for `Controller`, not just `PlayerController`, should we even have the `IsPlayerController` check ? Doesn't that check make the inclusion of finding just `Controller` irrelevant since we're looking for `PlayerController` as well anyway ?
> 
> A player controller is not just the APlayerController class. As you guys said, a game can have a custom controller for the player built on top of the `AController`. Therefore, the `AController` itself has a `bIsPlayerController` flag and the `IsPlayerController` function to determine that it is a controller that should control a player and not an NPC.

I wasn't aware of this bool, thanks.



> > Considering we're checking for `Controller`, not just `PlayerController`, should we even have the `IsPlayerController` check ? Doesn't that check make the inclusion of finding just `Controller` irrelevant since we're looking for `PlayerController` as well anyway ?
> 
> Yeah, that is my point. I don't think we can rely on devs marking their non-pc controller class as IsPlayerController.

I think if they've gone through with this kind of change (of a base system), then it's probably very likely a lot of other things will also have been changed which means a user will have to make lots of changes regardless.
I'm not sure if it's appropriate to try to cater to such games in base UE4SS, but I do realize that if there's no reason for the restriction, then the restriction should not exist which is something for @igromanru to answer.

**Comment by narknon** [comment]
We also do support 4.11 and nearly support 4.10.

**Comment by igromanru** [comment]
> > Considering we're checking for `Controller`, not just `PlayerController`, should we even have the `IsPlayerController` check ? Doesn't that check make the inclusion of finding just `Controller` irrelevant since we're looking for `PlayerController` as well anyway ?
> 
> Yeah, that is my point. I don't think we can rely on devs marking their non-pc controller class as IsPlayerController.

On what can we rely then? Can we rely on [APawn:IsPlayerControlled()](https://github.com/UE4SS-RE/RE-UE4SS/blob/d935b5b23bac03b65c14ae38382b02007204cc2e/assets/Mods/shared/UEHelpers/UEHelpers.lua#L41) (Like it was before)? In my opinion it's simply not worth it to cover these few games that don't use `APlayerController` class as their base. I remember seeing games that changed the UE base code a lot before 4.25, but after that it became very rare. Haven't seen much since 4.27.   
I think it's safe to assume that if some game developers for some reason ignore APlayerController and base their player controller on AController, they will still mark it as a player controller.

> We also do support 4.11 and nearly support 4.10.
> 
> Edit: Though that's what your backup IsLocal is intended for.

If you can tell me few games examples I would be happy to download them and test it. I just have hard time to come up with such games. The game with oldest Engine that I remember was Sea of Thieves which was based on 4.12, but it's an online only game with EAC.

> I think if they've gone through with this kind of change (of a base system), then it's probably very likely a lot of other things will also have been changed which means a user will have to make lots of changes regardless. I'm not sure if it's appropriate to try to cater to such games in base UE4SS, but I do realize that if there's no reason for the restriction, then the restriction should not exist which is something for @igromanru to answer.

I agree that we should support as many games as possible, especially if the UE has extra handling for the cases mentioned. But at the same time, we need a baseline. We need to be able to trust in something. Right now, I trust that game developers will adhere to the Unreal Engine standards and mark their own player controllers as `bIsPlayerController`. And if they don't, well, UEHelpers is not a major part of UE4SS, at worst people will have to come up with their own functions.  
Even if we finally find games like this again, UEHelpers can always be “fixed”/improved. Looking at the issues log, I can tell that most people have bigger problems getting UE4SS to work than with the functionality of UEHelpers.

**Comment by igromanru** [comment]
To be honest, I doubt that current UE4SS supports 10 old Unreal Engine versions.  
I just downloaded the game [Daylight](https://store.steampowered.com/app/230840/Daylight/). No idea which UE4 version it has exactly, but a very old one. The game is from 2014.
```
[2024-10-04 18:56:03.4999703] PS Scan attempt 1
[2024-10-04 18:56:03.5000020] [PS] Reading image
[2024-10-04 18:56:03.5000778] [PS] Starting scan
[2024-10-04 18:56:03.5209992] [PS] Scan finished in 20.8876ms
[2024-10-04 18:56:03.5210313] [PS] Failed to find EngineVersion: expected at least one value
[2024-10-04 18:56:03.5210398] [PS] You need to override the engine version in 'UE4SS-settings.ini'.
[2024-10-04 18:56:03.5210470] [PS] Failed to find GUObjectArray: expected at least one value
[2024-10-04 18:56:03.5210527] [PS] You can supply your own AOB in 'UE4SS_Signatures/GUObjectArray.lua'
[2024-10-04 18:56:03.5210614] [PS] Failed to find GMalloc: expected at least one value
[2024-10-04 18:56:03.5210679] [PS] You can supply your own AOB in 'UE4SS_Signatures/GMalloc.lua'
[2024-10-04 18:56:03.5210733] [PS] Failed to find FName::ToString: expected at least one value
[2024-10-04 18:56:03.5210795] [PS] You can supply your own AOB in 'UE4SS_Signatures/FName_ToString.lua'
[2024-10-04 18:56:03.5210867] [PS] Failed to find FName::FName(wchar_t*): expected at least one value
[2024-10-04 18:56:03.5210932] [PS] You can supply your own AOB in 'UE4SS_Signatures/FName_Constructor.lua'
[2024-10-04 18:56:03.5211021] [PS] Failed to find StaticConstructObject_Internal: expected at least one value
[2024-10-04 18:56:03.5211084] [PS] You can supply your own AOB in 'UE4SS_Signatures/StaticConstructObject.lua'
[2024-10-04 18:56:03.5211141] [PS] Failed to find FText::FText(FString&&): expected at least one value
[2024-10-04 18:56:03.5211192] [PS] You can supply your own AOB in 'UE4SS_Signatures/FText_Constructor.lua'
[2024-10-04 18:56:03.5211257] [PS] Scan failed
```

If anyone knows an old game that UE4SS was working with, let me know.

**Comment by igromanru** [comment]
[Kholat](https://store.steampowered.com/app/343710/Kholat/) UE v4.7.5.3
```
[2024-10-04 19:26:12.8362075] PS Scan attempt 1
[2024-10-04 19:26:12.8362403] [PS] Reading image
[2024-10-04 19:26:12.8363193] [PS] Starting scan
[2024-10-04 19:26:12.9072915] [PS] Scan finished in 70.9423ms
[2024-10-04 19:26:12.9073172] [PS] Found EngineVersion: 4.7
[2024-10-04 19:26:12.9073293] [PS] Failed to find GUObjectArray: expected at least one value
[2024-10-04 19:26:12.9073355] [PS] You can supply your own AOB in 'UE4SS_Signatures/GUObjectArray.lua'
[2024-10-04 19:26:12.9073431] [PS] Found GMalloc: 0x7ff73a426978
[2024-10-04 19:26:12.9073480] [PS] Found FName::ToString: 0x7ff738929270
[2024-10-04 19:26:12.9073538] [PS] Found FName::FName(wchar_t*): 0x7ff73891a630
[2024-10-04 19:26:12.9073608] [PS] Failed to find StaticConstructObject_Internal: expected at least one value
[2024-10-04 19:26:12.9073665] [PS] You can supply your own AOB in 'UE4SS_Signatures/StaticConstructObject.lua'
[2024-10-04 19:26:12.9073734] [PS] Failed to find FText::FText(FString&&): expected at least one value
[2024-10-04 19:26:12.9073782] [PS] You can supply your own AOB in 'UE4SS_Signatures/FText_Constructor.lua'
[2024-10-04 19:26:12.9073854] [PS] Scan failed
```

**Comment by narknon** [comment]
It says in the readme the versions we support and PS scans aren't related to support

**Comment by igromanru** [comment]
> It says in the readme the versions we support and PS scans aren't related to support

If PS doesn't support a game, it means that UE4SS doesn't work out of the box. If it doesn't work per default we can't ensure backwards compatibility. If we can't even test UEHelpers what guarantees that the previous version worked for all the older games?  
So far, the additional codes and tests are based on speculation.  
I believe you that you saw games that used AController only and that UE4SS worked for old games, but so far nobody could recall a single game where it was the case.  
So the question arises, is it worth building compatibility purely on fleeting memories?  
I have a feeling that UEHelpers is currently under the microscope because I made changes there, but when was the last time UE4SS was tested with the mentioned games that require special handling?  
If it's so important to support that 0.01% of games you can't even name, shouldn't every UE4SS change be tested against them?

**Comment by UE4SS** [comment]
> > It says in the readme the versions we support and PS scans aren't related to support
> 
> If PS doesn't support a game, it means that UE4SS doesn't work out of the box. If it doesn't work per default we can't ensure backwards compatibility. If we can't even test UEHelpers what guarantees that the previous version worked for all the older games? So far, the additional codes and tests are based on speculation. I believe you that you saw games that used AController only and that UE4SS worked for old games, but so far nobody could recall a single game where it was the case. So the question arises, is it worth building compatibility purely on fleeting memories? I have a feeling that UEHelpers is currently under the microscope because I made changes there, but when was the last time UE4SS was tested with the mentioned games that require special handling? If it's so important to support that 0.01% of games you can't even name, shouldn't every UE4SS change be tested against them?

I think if no game can be found to test with, we should merge this and fix any potential problems in the future if this change is actually found to be problematic.

**Comment by igromanru** [comment]
> I think if no game can be found to test with, we should merge this and fix any potential problems in the future if this change is actually found to be problematic.

If you ask me, I think it's overall the best approach for the project, UE4SS isn't an enterprise software and due to the fluid nature of  games UE4SS can't guarantee to work even for all modern games with supported Engine version. Not to mention the lack of manpower.  
As I said, I want to deliver the best possible work and would like to test it more thoroughly, but I simply can't find an environment where UE4SS itself works but not the changes I made.

**Comment by igromanru** [comment]
Over a week hast past. Any news here?  
I've so far reviews UEHelpers once again and found no logic errors.

**Review by UE4SS — APPROVED** [review]
I'll merge this soon, I want to give @narknon a last chance to disagree, probably a day or two at most if no more discussions are had about this.

**Pull request merged**
