### PR TITLE
Add xmake ci --dump command

### PR DESCRIPTION
**Pull request by bitonality**
# Proposed new xmake commands

`xmake ci --dump=targets`
<details><summary>Expand to show result</summary>

```json
{"File":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\File\\File.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\File\\File.lib"},"DynamicOutput":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\DynamicOutput\\DynamicOutput.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\DynamicOutput\\DynamicOutput.lib"},"LuaRaw":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\LuaRaw\\LuaRaw.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\LuaRaw\\LuaRaw.lib"},"KismetDebuggerMod":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\KismetDebuggerMod\\KismetDebuggerMod.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\KismetDebuggerMod\\KismetDebuggerMod.dll"},"Unreal":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\Unreal\\Unreal.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\Unreal\\Unreal.lib"},"JSON":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\JSON\\JSON.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\JSON\\JSON.lib"},"ParserBase":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\ParserBase\\ParserBase.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\ParserBase\\ParserBase.lib"},"Helpers":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\Helpers\\Helpers.pdb"},"proxy":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\proxy\\dwmapi.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\proxy\\dwmapi.dll"},"ArgsParser":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\ArgsParser\\ArgsParser.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\ArgsParser\\ArgsParser.exe"},"proxy_generator":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\proxy_generator\\proxy_generator.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\proxy_generator\\proxy_generator.exe"},"ScopedTimer":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\ScopedTimer\\ScopedTimer.pdb"},"Function":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\Function\\Function.pdb"},"Constructs":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\Constructs\\Constructs.pdb"},"MProgram":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\MProgram\\MProgram.pdb"},"ASMHelper":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\ASMHelper\\ASMHelper.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\ASMHelper\\ASMHelper.lib"},"IniParser":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\IniParser\\IniParser.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\IniParser\\IniParser.lib"},"SinglePassSigScanner":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\SinglePassSigScanner\\SinglePassSigScanner.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\SinglePassSigScanner\\SinglePassSigScanner.lib"},"patternsleuth_bind":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\patternsleuth_bind\\patternsleuth_bind.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\patternsleuth_bind\\patternsleuth_bind.lib"},"Profiler":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\Profiler\\Profiler.pdb"},"UE4SS":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\UE4SS\\UE4SS.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\UE4SS\\UE4SS.dll"},"LuaMadeSimple":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\LuaMadeSimple\\LuaMadeSimple.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\LuaMadeSimple\\LuaMadeSimple.lib"},"glad":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\glad\\glad.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\glad\\glad.lib"},"Input":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\Input\\Input.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\Input\\Input.lib"},"UVTD":{"symbol":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\UVTD\\UVTD.pdb","target":"H:\\bito_ue4ss_staged\\Binaries\\Game__Dev__Win64\\UVTD\\UVTD.exe"}}
```
</details>

---

`xmake ci --dump=modes`

```json
["Game__Dev__Win64","Game__Debug__Win64","CasePreserving__Dev__Win64","CasePreserving__Test__Win64","CasePreserving__Debug__Win64","CasePreserving__Shipping__Win64","Game__Shipping__Win64","Game__Test__Win64"]
```

---

These are foundational commands that allow us to safely query xmake for information about the build. This will be used by CI to determine expected files and can also be used in future scripting since the output is in JSON format and easily parseable. The dump subcommand is easily extensible and future functionality can be added to the `xmake ci` command as needs change in the future.

### CODE REVIEW

**Comment by narknon** [comment]
Please document

**Comment by bitonality** [comment]
> Please document

Usage documentation or inline documentation?

This is how it currently fits in with existing xmake commands.

xmake-ci

xmake-ci-dump

**Comment by narknon** [comment]
I'd like if all of our xmake customizations could end up in the web docs, including explanations of the 'rules'

**Review by narknon — APPROVED** [review]

**Comment by narknon** [comment]
Merging with request that all xmake commands and custom features be added to our online docs before next release.

**Pull request merged**
