### PR TITLE
fix: correct typos, unify path formats and clarify some explanations

### PR DESCRIPTION
**Pull request by massclown**
Minor documentation changes, mostly around requirements/prerequisites, why things are done like this, and how to verify that everything is running.

### CODE REVIEW

**Comment by Buckminsterfullerene02** [comment]
Looks good to me. While you're at it, can you remove these three duplicated entires from C++ API in `SUMMARY.md`? They should only be in the guides section (to be in-line with the Lua API guides/section). Eventually the C++ API section should be populated with actual documentation on the macros and other nice things for the C++ API but no one has gotten round to doing it yet.
```
  - [Creating a C++ Mod](./guides/creating-a-c++-mod.md)
  - [Installing a C++ Mod](./guides/installing-a-c++-mod.md)
  - [GUI tabs with a C++ Mod](./guides/creating-gui-tabs-with-c++-mod.md)
 ```

**Comment by massclown** [comment]
Thanks, removed these duplicates for now.

**Comment by narknon** [comment]
> Looks good to me. While you're at it, can you remove these three duplicated entires from C++ API in `SUMMARY.md`? They should only be in the guides section (to be in-line with the Lua API guides/section). Eventually the C++ API section should be populated with actual documentation on the macros and other nice things for the C++ API but no one has gotten round to doing it yet.
> 
> ```
>   - [Creating a C++ Mod](./guides/creating-a-c++-mod.md)
>   - [Installing a C++ Mod](./guides/installing-a-c++-mod.md)
>   - [GUI tabs with a C++ Mod](./guides/creating-gui-tabs-with-c++-mod.md)
> ```

I preferred having these in both places.

**Comment by massclown** [comment]
I can revert the last commit in my branch and bring the duplicate links back, and I can take a stab at writing the C++ API docs as well, just in a later PR (so they can be put in the C++ section where the duplicate links were). What do you think?

**Comment by Buckminsterfullerene02** [comment]
Yeah just revert that commit then. Don't wanna cause a silly debate about duplicate links vs non-duplicate links. Let's get this merged and then you can work on C++ API docs as well.

**Comment by massclown** [comment]
Done, thanks

**Pull request merged**
