### PR TITLE
feat: UE 5.4 support

### PR DESCRIPTION
**Pull request by UE4SS**
**Description**

Adds support for UE 5.4.

This also improves one of the error messages related to Luas UScriptStruct implementation, which turned out to be useful when diagnosing why UE4SS wasn't working in 5.4.

**Type of change**

- [x] New feature (non-breaking change which adds functionality)

**Checklist**

Please delete options that are not relevant. Update the list as the PR progresses.

- [x] Any dependent changes have been merged and published in downstream modules.

**Additional context**

Requires https://github.com/Re-UE4SS/UEPseudo/pull/90.
See #502 for status updates.
This is currently blocked until we test BP mods.

### CODE REVIEW

**Comment by UE4SS** [comment]
I believe this is now ready, together with Re-UE4SS/UEPseudo#90.

**Review by Buckminsterfullerene02 — APPROVED** [review]

**Comment by miek801** [comment]
https://store.steampowered.com/app/2397300/Half_Sword/   This game is Unreal version 5.4.4. I have tried many methods but cannot recognize my blueprint Mod. The log prompts: Actor for mod 'MMode' is not valid.

**Comment by narknon** [comment]
> [store.steampowered.com/app/2397300/Half_Sword](https://store.steampowered.com/app/2397300/Half_Sword/) This game is Unreal version 5.4.4. I have tried many methods but cannot recognize my blueprint Mod. The log prompts: Actor for mod 'MMode' is not valid.

Do not spam all of our issues.

**Comment by miek801** [comment]
> > [store.steampowered.com/app/2397300/Half_Sword](https://store.steampowered.com/app/2397300/Half_Sword/) This game is Unreal version 5.4.4. I have tried many methods but cannot recognize my blueprint Mod. The log prompts: Actor for mod 'MMode' is not valid.
> 
> Do not spam all of our issues.

I'm sorry, I understand. I'm sorry to bother you. There won't be a next time.

**Comment by ayaantahir564** [comment]
u

**Pull request merged**
