### PR TITLE
fix: Mod directory being used before it's setup

### PR DESCRIPTION
**Pull request by UE4SS**
**Description**

This fixes `ModsFolderPath` in `UE4SS-settings.ini` being broken.

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

Move `Binaries/Win64/Mods` to ~~`Binaries/Mods`~~`Content/Paks/Mods`, and set `ModsFolderPath` to `../../Content/Paks/Mods`.

**Checklist**

Please delete options that are not relevant. Update the list as the PR progresses.

- [x] I have added the necessary description of this PR to the changelog, and I have followed the same format as other entries.

### CODE REVIEW

**Comment by Buckminsterfullerene02** [comment]
This does not work for me. And your test case seems weird as `Mods` are in `Binaries/Win64/ue4ss/Mods`.

Default directory is `<UE4SS.dll directory>/Mods`. I tested moving `Mods` into `Content/Paks` folder and set override path config to `../../Content/Paks/Mods`, it doesn't find mods and there is no error. If I set it to `../../../Content/Paks/Mods` I get `Error: directory_iterator::directory_iterator: unknown error: "../../../Content/Paks/Mods"`. The latter is the correct path.

image

I do not have any `override.txt` file.

**Comment by UE4SS** [comment]
> This does not work for me. And your test case seems weird as `Mods` are in `Binaries/Win64/ue4ss/Mods`. If I set mine to `../../Mods` and move `Mods` into `Binaries/Mods` it does not find mods and there is no error.
> 
> Default directory is `<UE4SS.dll directory>/Mods`. I tested moving `Mods` into `Content/Paks` folder and set override path config to `../../Content/Paks/Mods`, it doesn't find mods and there is no error. If I set it to `../../../Content/Paks/Mods` I get `Error: directory_iterator::directory_iterator: unknown error: "../../../Content/Paks/Mods"`. The latter is the correct path.
> 
> image
> 
> I do not have any `override.txt` file.

Okay obviously I typo'd it, I meant to say that I moved `Mods` into `Content/Paks`.
As far as that error, the path is from the Win64 dir, not the ue4ss dir.

**Comment by UE4SS** [comment]
Note that there's another problem with the mod directory override that I'm currently working on.
I'll update this PR.

**Comment by UE4SS** [comment]
This is now ready for testing again.

**Comment by UE4SS** [comment]
I've updated my test-case, sorry again for messing that up.

**Review by Buckminsterfullerene02 — APPROVED** [review]

**Pull request merged**
