### PR TITLE
chore: remove Windows.h from CrashDumper

### PR DESCRIPTION
**Pull request by localcc**
**Description**

Cleanup CrashDumper to not include Windows.h and not use polyhook in headers.

**Type of change**

- [x] Other... Please describe: header cleanup

**How Has This Been Tested?**

Compiling the project after the change.

### CODE REVIEW

**Review by UE4SS — DISMISSED** [review]

**Review by UE4SS — APPROVED** [review]
I guess there was a problem with the header order or something ?
I compiled this branch successfully before you re-ordered it.
Anyway, I re-compiled with the current state of the branch and it still compiles.

**Comment by localcc** [comment]
No problem with the order, was just fixing merge conflicts with main

**Comment by UE4SS** [comment]
It's irrelevant, I just saw [this](https://github.com/UE4SS-RE/RE-UE4SS/compare/e11483c9aba9062226cdb62a7a00996aa80b1ccc..dc7e60fe521500c563d391fb4287093622cd1565) which wasn't obvious to me to be a conflict resolution because I would've expected that to be in the merge commit before the force push.

**Comment by localcc** [comment]
Yeah just wanted a cleaner history without a merge commit so I rebased

**Pull request merged**
