### PR TITLE
Fixed Key::NUM_ZERO being mapped incorrectly to NUM_NINE

### LINKED ISSUE #633: [BUG - main] Incorrect value for Key.NUM_ZERO
**Branch or Release**
1b5ff7739601f504d7563b280185eae267bdc047

**Game and Engine Version**
N/A

**Describe the bug**
https://github.com/UE4SS-RE/RE-UE4SS/blob/1b5ff7739601f504d7563b280185eae267bdc047/UE4SS/src/Mod/LuaMod.cpp#L458

`VK_NUMPAD0` is 0x60 but it's defined as 0x69 (`VK_NUMPAD9`) in the base code.

**Mods directory**
N/A

**To Reproduce**
N/A

**Expected behavior**
```cpp
key_table.add_pair("NUM_ZERO", 0x60);
```

**Screenshots, UE4SS Log, and .dmp file**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by UE4SS**
Fixes #633

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by Buckminsterfullerene02 — APPROVED** [review]
Works for me

**Comment by 0-F** [comment]
I think I always have the problem, even with the latest experimental release (UE4SS_v3.0.1-272-g5015114.zip).
Maybe `UE4SS/src/Mod/LuaMod.cpp` and `assets/Mods/shared/Types.lua` need to be patched too?
Code search of NUM_ZERO: https://github.com/search?q=repo%3AUE4SS-RE%2FRE-UE4SS%20NUM_ZERO&type=code

**Comment by UE4SS** [comment]
> I think I always have the problem, even with the latest experimental release (UE4SS_v3.0.1-272-g5015114.zip). Maybe `UE4SS/src/Mod/LuaMod.cpp` and `assets/Mods/shared/Types.lua` need to be patched too? Code search of NUM_ZERO: https://github.com/search?q=repo%3AUE4SS-RE%2FRE-UE4SS%20NUM_ZERO&type=code

Yes, this was missed, thanks.

**Comment by UE4SS** [comment]
Lua fixed in #762

**Pull request merged**
