### PR TITLE
Port/strings Typedef

### PR DESCRIPTION
**Pull request by Yangff**
This PR just moves `StringType` from File to String.

Right now, CharType is set to `whcar_t`, for a verification build for Linux, one can try to build when it is set to `char16_t`.

It is not intended to solve the circlular dependency in this PR but we may someday as suggested by @localcc seperate Unreal module into Unreal and UnrealDef.

Once this is sovled, CharType should be set to `TCHAR` for normal build.

I think it's safe to say TCHAR will be UTF-16 at this point, if we want to support cases that TCHAR can be say... utf8/utf32.. then might need to wrap it with `to_string` or `to_wstring` based on platform/env.. or pull back the `to_system` macro for those cases..

I have not tested this change but cherrypick it from my current working branch as suggest by @narknon to allow this part to be easily reviewed and merged. I think this should be mostly okay but please check if it compiles.. 
In theory, it should not break anything because I re-exported everything under the `RC::File::` namespace.

It is based on the `fmt` PR although it may not actaully related. It is also possible to merge this before the fmt change.

These is nothing to document at this point, although future code should avoid use `File::*` for string/char type I think.

Also, please try to avoid the use of wstring unless needed.

### CODE REVIEW

**Comment by Yangff** [comment]
This depends on #565

**Comment by narknon** [comment]
Requires 
```
includes("String")
```
in deps\first\xmake.lua to build.

**Comment by narknon** [comment]
Also breaks anything referencing the old File ToString 
image

And requires the Unreal FMT branch to be merged.

**Comment by Yangff** [comment]
got it.. will steal some commits from another PR..

**Comment by narknon** [comment]
I merged fmt here and on uepseudo so these could be rebased onto main.

**Comment by Yangff** [comment]
image
I think this should build ... at least on my local.

**Review by UE4SS — APPROVED** [review]
Builds successfully for me, and the code looks good.

**Comment by Buckminsterfullerene02** [comment]
Both shipping and debug works on DRG with various tool functions, except debug crashes on UHT dump, but it also does in latest main commit, so it is not related to this PR and I will make a seperate issue for that.

**Pull request merged**
