### PR TITLE
Add a more comprehensive and detailed guide on how to fix missing AOBs

### PR DESCRIPTION
**Pull request by TimeMaster18**
**Description**

This PR adds a more comprehensive and detailed guide on how to fix missing AOBs in UE4SS by providing custom signatures and callbacks using Lua. It expands the existing documentation to cover additional steps, troubleshooting tips, and context for creating and applying custom AOB signatures. This update aims to improve the clarity and usability of the AOB fixing process, making it easier for users with basic reverse engineering knowledge to create their own signatures. There are no direct dependencies for this documentation change.

Requested from: https://github.com/UE4SS-RE/RE-UE4SS/issues/665#issuecomment-2395222212

Fixes # (no specific issue referenced)

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Is/requires documentation update
- [ ] Other... Please describe:

**How Has This Been Tested?**

N/A

**Checklist**

- [ ] I have commented my code, particularly in hard-to-understand areas. (Not applicable – documentation update)
- [x] I have made corresponding changes to the documentation.
- [ ] I have added the necessary description of this PR to the changelog, and I have followed the same format as other entries. (If a changelog exists for docs, I will add it.)
- [ ] Any dependent changes have been merged and published in downstream modules. (Not applicable – documentation only)

**Screenshots (if appropriate)**

N/A

**Additional context**

The new guide provides step-by-step instructions, additional context on why certain steps are necessary, and troubleshooting hints for when an AOB is not easily found. This should help reduce user confusion and provide a stronger foundation for those unfamiliar with reverse engineering tasks.

### CODE REVIEW

**Comment by UE4SS** [comment]
Well this is awkward, we just merged #712.

**Comment by narknon** [comment]
We should also merge this if possible without conflicts so Time gets credit for his writeup.

**Comment by UE4SS** [comment]
Well this is awkward, we just merged #712.

> We should also merge this if possible without conflicts so Time gets credit for his writeup.

Credit was given in the docs.

**Comment by narknon** [comment]
Not the same as commit authorship. But it's up to Time if he cares.

**Comment by Buckminsterfullerene02** [comment]
Haha oops. Oh well. I don't mind reverting #712 if Time wants the commit credit for it. Would be pretty hard to merge the two without conflicts, since they based off the same comment. But from quick glance this one is formatted properly and seems to contain even better info so I think best to have this one entirely by reverting my one.

**Comment by UE4SS** [comment]
> Haha oops. Oh well. I don't mind reverting #712 if Time wants the commit credit for it. Would be pretty hard to merge the two without conflicts, since they based off the same comment. But from quick glance this one is formatted properly and seems to contain even better info so I think best to have this one entirely by reverting my one.

If we do that, this PR also needs to update `SUMMARY.md` to add a link to the guide.

**Comment by Buckminsterfullerene02** [comment]
Oh, I was looking on phone earlier, and didn't notice this is a seperate page. What should we do, replace the current one with this? I don't see much point in having both pages if they explain the same thing.

Just one major query though, how much of the guide was written by chatgpt? I can see the last paragraph is very clearly written by it:

> By following these expanded steps and leveraging the provided tools, you’ll have a more comprehensive understanding of how to fix missing AOBs with UE4SS. Although still complex, this extended guide should help clarify the process and offer practical insights for both beginners and experienced modders venturing into reverse engineering territory.

And the `By following these expanded steps` suggests that the whole format of the page was generated by chatgpt and this was the last paragraph it generated. 

I'm not against using AI to format things, but I want to be sure, that there are no hallucinations created here, and that all steps provided in the guide are created by human, i.e. the steps are what @TimeMaster18 took to create this guide.

**Comment by TimeMaster18** [comment]
I don't mind either way, whatever is easiest for you guys.

I did see the commit/PR but I already had it mostly done so I finished and pushed it anyway.

**Comment by UE4SS** [comment]
@TimeMaster18 Not sure if you missed the question since you responded since then but without answering it.
If you missed the question, please re-read @Buckminsterfullerene02 comment above and respond.

**Comment by TimeMaster18** [comment]
I guess you mean the question about chatGPT?

I use AI for most tasks nowadays, so yes. The steps are true to what I posted on the other comment.

It is more likely that some details are missing or not very accurate from my still limited but improving knowledge about reverse engineering and the UE4SS framework. So if you like the format and style, please review that my post from the other day (or this guide based on it) doesn't have anything misleading or inaccurate. You all know this much better than me, so feel free to edit or add anything you see fit too.

AI isn't too useful for reverse engineering from what I could tell when trying to figure some things out. It's great at writing code and docs when given detailed descriptions and plenty of content.

**Comment by UE4SS** [comment]
I've changed some things in the guide, and removed sections that were duplicated from the basic guide to avoid having multiple places to modify in case things change in the future.

**Review by UE4SS — APPROVED** [review]

**Comment by UE4SS** [comment]
My changes also include the manual removal of the content added by #712

**Pull request merged**
