### PR TITLE
fix: use GitHub PAT to avoid 'early EOF' errors in workflow runner

### LINKED ISSUE #437: make experimental release bug
[make-release]
fetch-pack: invalid index-pack output
[make-release]
early EOF
[make-release]
fetch-pack: invalid index-pack output

### PR DESCRIPTION
**Pull request by Lyrth**
### Description

Use GitHub PAT (personal access token) to avoid 'early EOF' errors in workflow runner. This essentially replaces the use of SSH in the workflows.

Resolves #437.

### Required changes on GitHub for this PR:

- Generate a PAT on the user that holds [UEPseudo](https://github.com/Re-UE4SS/UEPseudo), either a "fine-grained token" or a "classic token" (more on that below), under Settings, Developer Settings, Personal access tokens.
- Add the PAT to RE-UE4SS repository action secrets (under repo's Settings, Secrets and variables, Actions), with secret name being `UEPSEUDO_PAT`, and with the personal access token as the value.

Note: The SSH key is still used in other workflows other than experimental and release.

Personal access tokens can be either classic or fine-grained. __**Fine-grained tokens**__ allows for read-only access to private repositories you specify that the user is a (direct) owner of, but has an expiration date of 1 year at most, and *will need* to be regenerated and replaced when it expires. __**Classic tokens**__ can be specified to never expire, but has less control over access - to be able to *just* read private repositories, *full `repo` access* must be given to the token, i.e., read/write access to user repositories.

**Configuration of the token:**
<details>
<summary><i>Configuration for Fine-grained tokens</i></summary>
<ul>
<li>Everything is default unless specified</li>
<li><b><u>Name:</u></b>  any descriptive name</li>
<li><b><u>Expiration:</u></b>  to preference, at most 1 year</li>
<li><b><u>Repository access:</u></b>  Only select repositories. Add <b>UEPseudo</b> into the selection list. RE-UE4SS does not need to be selected as long as it remains a public repository.</li>
<li><b><u>Permissions:</u></b>  Under Repository permissions, set <b>Contents</b> to Access: Read-only.</li>
<li>Overview should now say "2 permissions for 1 of your repositories" (Contents and Metadata). Generate the token.</li>
</ul>
</details>

<details>
<summary><i>Configuration for Classic tokens</i></summary>
<ul>
<li>Everything is default unless specified</li>
<li><b><u>Note:</u></b>  any descriptive name</li>
<li><b><u>Expiration:</u></b>  to preference, indefinite expiration is allowed</li>
<li><b><u>Select scopes:</u></b>  <b>repo</b> checkbox must be checked. Will also unconditionally enable the options below it.</li>
<li>Generate the token.</li>
</ul>
</details>

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

All 7 test workflow runs have passed the Checkout step with no git 'early EOF' errors nor retries.

[Complete workflow run 1](https://github.com/Lyrth/RE-UE4SS/actions/runs/8629858934/job/23654896383#step:2:43) - using fine-grained PAT
[Workflow run 2](https://github.com/Lyrth/RE-UE4SS/actions/runs/8629878126/job/23654953321#step:2:43) - using fine-grained PAT - cancelled after the Checkout step succeeded to save resources.
[Workflow run 3](https://github.com/Lyrth/RE-UE4SS/actions/runs/8629888452/job/23654983254#step:2:43) - ^
[Workflow run 4](https://github.com/Lyrth/RE-UE4SS/actions/runs/8629900046/job/23655017554#step:2:43) - ^
[Workflow run 5](https://github.com/Lyrth/RE-UE4SS/actions/runs/8629913808/job/23655059496#step:2:43) - ^
[Workflow run 6](https://github.com/Lyrth/RE-UE4SS/actions/runs/8630051426/job/23655513762#step:2:43) - using classic PAT - also cancelled after the Checkout step succeeded.
[Workflow run 7](https://github.com/Lyrth/RE-UE4SS/actions/runs/8630063926/job/23655555371#step:2:43) - ^

**Checklist**

- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by localcc** [comment]
What's the status on this?

**Comment by UE4SS** [comment]
> What's the status on this?

As far as I know, we're waiting on @narknon to configure the token before this is merged so that our CI doesn't break.

**Comment by UE4SS** [comment]
> I've asked him to do it at least 3 times and he just ghosts me every time so I simply don't know what his problem is... Maybe he thinks it's to do with xmake which he doesn't like, but it's got nothing to do with xmake as this problem has been happening for many months.

How long have you been trying to get him to do it ? Right after this PR was created ?
Also, has he been particularly inactive during this time ?

**Comment by Buckminsterfullerene02** [comment]
Right after the PR was created, I've mentioned him in GitHub and in UE4SS server, both places he has been active in since. He's reviewed, commented on and merged other PRs around this one so there's no way he hasn't seen this.

**Comment by UE4SS** [comment]
> Right after the PR was created, I've mentioned him in GitHub and in UE4SS server, both places he has been active in since. He's reviewed, commented on and merged other PRs around this one so there's no way he hasn't seen this.

That's very frustrating.
If he has a reason for not wanting this PR to be merged, he should tell us.
If he's just needlessly blocking this PR then what do we do ? That would be a very hostile thing to do, and I'm not sure what do to about it, but I certainly don't want to let this (or any) PR be blocked without reason.

**Comment by Buckminsterfullerene02** [comment]
Yeah that's what I mean I just don't get it. I can't possibly think of what reason there is to ignore it.

**Comment by localcc** [comment]
A semi-related question, why do we have uepseudo as a separate user, and not an organization? And another question would be why do we even need a separate user if we could host the fork in this repository?

**Comment by UE4SS** [comment]
> A semi-related question, why do we have uepseudo as a separate user, and not an organization? And another question would be why do we even need a separate user if we could host the fork in this repository?

Could there be some permission problem ? The UEPseudo repo is a bit special because it's literally a fork of UE (so that everyone requires an Epic account) that's been cleaned out, perhaps it was easier to create the fork with a non-org account or something.
This is just a guess though, I really don't know at all.

**Comment by localcc** [comment]
From my testing, github allows us to fork unreal onto an organization account, so maybe we should switch that to this org / create a separate org just for the unreal fork, so several people can have permissions.

**Comment by UE4SS** [comment]
> From my testing, github allows us to fork unreal onto an organization account, so maybe we should switch that to this org / create a separate org just for the unreal fork, so several people can have permissions.

Well if there's no problem with having it in this org, then if a move is happening it should be to this org in my opinion.
Whether a move should happen or not is another question.
How would developers (including mod developers) be affected by the repo changing ? Do they have to manually change the remote on their local repos or does git take care of this automatically ?
If people have to manually make a change, I foresee lots of problems in the future about outdated (and eventually non-compiling) UEPseudo code as people might not even realize (or otherwise won't know how) that they need to change the remote.

**Comment by localcc** [comment]
From my understanding, if we update the submodule in here, users will get the change automatically when doing `git submodule update --init --recursive` (which they should be doing each pull so that the unreal submodule gets fetched)

**Comment by UE4SS** [comment]
> From my understanding, if we update the submodule in here, users will get the change automatically when doing `git submodule update --init --recursive` (which they should be doing each pull so that the unreal submodule gets fetched)

What about users that use the alternative way of updating by cd'ing into `deps/first/Unreal` and doing `git pull`, and also users that make forks and are constantly checking out different ones ? I guess we could assume that they know what they're doing and can solve any git problem on their own as long as we let them know about the change.
Users that don't have permission to make forks directly in UEPseudo will obviously have to re-fork and set up their stuff again as well I think.

Wouldn't it be easier to add multiple people to the UEPseudo repo with the appropriate access ?

**Comment by narknon** [comment]
Multiple people already have access to the UEPseudo repo.  I'm pretty sure I'm not the only one that can do this.  No, it cannot be moved into an organization account because that would violate UE's license.  As far as how active I've been, I haven't been active.  Talking in discord or merging a few simple PRs doesn't mean I'm following everything, but thanks for making a ton of assumptions about me in a public PR.

**Review by narknon — APPROVED** [review]

**Comment by UE4SS** [comment]
> Multiple people already have access to the UEPseudo repo.

Could you check and let us know who, so that we know who to ask in the future ?
I know I don't have access.

**Comment by narknon** [comment]
You definitely have at least Write access.  I'm not sure if Admin or actual ownership is required for PATs.

**Comment by Buckminsterfullerene02** [comment]
Only the account that owns UEPseudo can make a PAT for UEPsuedo, since it's in the account settings rather than repository settings.

**Pull request merged**
