### PR TITLE
Add 5.05 support; fix FOptionalProperty support for 5.4

### PR DESCRIPTION
**Pull request by narknon**
Add 505 pdb to uvtd

Add updated templates

Add support for TOptional/FOptionalProperty

Update UE Submodule

### CODE REVIEW

**Comment by igromanru** [comment]
Any game suggestions to test with a UE 5,5 game?

**Comment by narknon** [comment]
> Any game suggestions to test with a UE 5,5 game?

Nope, but tested on my fake game.  Mostly just want to make sure it doesn't break other versions.  If it ends up being broken for 5.5 we'll care about that when some 5.5 games are out.

**Comment by igromanru** [comment]
I tested it in Hogwarts Legacy (4.27) and Abiotic Factor (5.4) few days ago. I haven't played long, but it worked and all the mods I had worked too.

**Comment by narknon** [comment]
Cool, thanks.

**Comment by ggoo01** [comment]
dfsdf

**Comment by harryasscrac** [comment]
url wont load

**Comment by KNIGA333** [comment]
> Contributor

**Comment by ferkose** [comment]
hello how can i download?

**Comment by 34288** [comment]
> 有什么游戏建议可以用来测试使用UE 5.5的游戏吗？
kards，ue5.5

**Comment by 34288** [comment]
> 有什么游戏建议可以用来测试使用UE 5.5的游戏吗？
怎么是2024年，你还在线吗

**Comment by narknon** [comment]
> > 有什么游戏建议可以用来测试使用UE 5.5的游戏吗？
> 怎么是2024年，你还在线吗
> 

I don't get what you're asking. This was merged a long time ago. We have support for 5.5 in experimental builds.

**Comment by 34288** [comment]
> > > 有什么游戏建议可以用来测试使用UE 5.5的游戏吗？
> > > 怎么是2024年，你还在线吗
> 
> I don't get what you're asking. This was merged a long time ago. We have support for 5.5 in experimental builds.

Wow, you are still online, but I tried it and it didn't work. The game needs to be launched through Steam. Because it is in Chinese, I thought you were not online, so I didn't use English. The game is kards

**Comment by 34288** [comment]
> > > 有什么游戏建议可以用来测试使用UE 5.5的游戏吗？
> > > 怎么是2024年，你还在线吗
> 
> I don't get what you're asking. This was merged a long time ago. We have support for 5.5 in experimental builds.

Boss, the main problem is that there is no output. I also failed using this "DLL Injector.exe"

**Comment by 34288** [comment]
> > > > 有什么游戏建议可以用来测试使用UE 5.5的游戏吗？
> > > > 怎么是2024年，你还在线吗
> > 
> > 
> > I don't get what you're asking. This was merged a long time ago. We have support for 5.5 in experimental builds.
> > Wow, you are still online, but I tried it and it didn't work. The game needs to be launched through Steam. Because it is in Chinese, I thought you were not online, so I didn't use English. The game is kards

I have been using this software for many years, and you are the first one to answer me, and it has been several years. I am so excited.

**Comment by narknon** [comment]
Please create a new issue for tracking. I'm also unsure what DLL Injector.exe is, we don't have anything like that. Are you sure you're on the right GitHub?

**Comment by narknon** [comment]
Actually, that game is competitive multiplayer. We do not support it.

**Comment by 34288** [comment]
> Actually, that game is competitive multiplayer. We do not support it.



> 实际上，那款游戏是具有竞争力的多人游戏。我们不支持它。

你早说就好了吗，我靠，你还会说中文，太爱了，我只是需要映射文件

**Comment by 34288** [comment]
> 请创建一个新的问题来跟踪。我也不确定DLL Injector.exe是什么，我们没有类似的东西。你确定你是在正确的GitHub上吗？

是的，我不怎么会用这个软件，因为中国有墙，跟世界隔绝就跟朝鲜一样，我们注册国外软件很难，因为发短信验证码这些发不到中国

**Comment by 34288** [comment]
> 实际上，那款游戏是具有竞争力的多人游戏。我们不支持它。

为什么多人游戏你就不行，太虚了，这个游戏都有很多人破解了，你这么晚还在线

**Comment by 34288** [comment]
> 请创建一个新的问题进行跟踪。我也不确定DLL Injector.exe是什么，我们没有类似的东西。你确定你访问的是正确的GitHub吗？



> 实际上，那款游戏是具有竞争力的多人游戏。我们不支持它。
Sorry, I translated it automatically, I thought you were speaking Chinese

**Comment by 34288** [comment]
That's all for now. I hope you're happy.goodbye

**Comment by 34288** [comment]
> Actually, that game is competitive multiplayer. We do not support it.

Is there any other way? Please, sir. Because I have searched the entire Chinese Internet and can't find it, you are my only hope, I want to get the mapping file to extract the pak

**Pull request merged**
