### PR TITLE
Add github alerts pre-processor to mdbook

### PR DESCRIPTION
**Pull request by Buckminsterfullerene02**
**Description**

Add github alerts pre-processor which allows markdown such as [!IMPORTANT] and [!WARNING] to work in mdbook. 

README in docs currently not supporting this so is a bit difficult to read.

**Type of change**

- [x] New feature (non-breaking change which adds functionality)
- [x] Is documentation update

**How Has This Been Tested?**

Tested changes on own fork of repo.

**Checklist**

- [x] I have made corresponding changes to the documentation.
- [x] I have added the necessary description of this PR to the changelog, and I have followed the same format as other entries.

### CODE REVIEW

**Comment by igromanru** [comment]
What's with all the old RPs that are dangling?  
I mean, is it done? Who has to review it? Can it be merged?

**Comment by UE4SS** [comment]
> What's with all the old RPs that are dangling? I mean, is it done? Who has to review it? Can it be merged?

It's an open source project that people work on in their spare time and people either:
A. Have no time to do a review.
B. Lack the motivation to do a review or potentially even work on the project at all.
C. Lack the knowledge to do a proper review.
D. Lack the ability to do a review because the project doesn't build for them.

For this particular PR, I'm `C` (don't know mdbook) and for most other PRs I'm also `D`.

**Comment by igromanru** [comment]
If nothing happens in their RPs for months, people lose touch with what they've done and lose the motivation to contribute more.  
If nobody but the creator of the PR has ABCD someone with authority has to make a decision if the change is at least in theory good and if the OP is trusted enough to make the change.  
I doubt that new contributors will suddenly appear who understand the project better than the people already working on it, and who will be in a position to decide what happens to old RPs.  
And since there are only few people who constantly work on the project I personally would just test some changes in "production".  
There are lot more mod devs who report issues than UE4SS Devs to test every change thoroughly.  
Experimental versions exist for good reasons, and I think they are allowed to have potential bugs that can be found by users.  
I don't blame anyone, I just think that circumstances requires a less professional approach to get things done. Nothing bad will happen if bugs need to be fixed in `main`.

**Comment by narknon** [comment]
Thanks for pinging that this has grown stale, but move conversation unrelated to the content of the PR elsewhere.

**Comment by Buckminsterfullerene02** [comment]
To get this merged, I will tell you how you can very easily test it (copy commands from the pushdocs.yml...):
1. Check out alerts-preprocessor branch
2. Open cmd on RE-UE4SS repo
3. Run following commands in order:
`cargo binstall --no-confirm mdbook-mermaid`
`mdbook-mermaid install docs-export/`
`cargo binstall --no-confirm mdbook-alerts`
`python docs-export/export.py`
`python docs-repo/build.py`
4. Open `docs-repo/docs/` and then open index.html and view readme, there you can see the preprocessor doing its thing
5. If you check any of the index.html in other areas (dev or versions) of course the readme is always there because of that bug that readme is always the same regardless of the commit (maybe someone will fix one day). but anyway preprocessor works for those too.

**Review by narknon — APPROVED** [review]

**Pull request merged**
